# Setup Postgres

version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: saituri
      TZ: 'UTC'
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - db_dev:/var/lib/postgresql/data
volumes:
  db_dev:
    driver: local

