# Setup Postgres

version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    expose:
      - "$DB_PORT"
    volumes:
      - db:/var/lib/postgresql/data
    command: -p ${DB_PORT}

  app:
    build: .
    depends_on:
      - db
    restart: always
    command: sh -c "yarn db:migrate && yarn backend:start-prod"
    ports:
      - ${HOST}:${PORT}:${PORT}
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}
      TZ: ${TZ}
      PORT: ${PORT}
      NODE_ENV: production
      BASIC_AUTH_USER: ${BASIC_AUTH_USER}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}

volumes:
  db:
    driver: local
